language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  # - "2.7"
  # - "3.5"
  - "3.7"

#install:
#  - conda env create --file environment.yml
#  - source activate fiduceo-user-tools-env
#
#script:
#  # For the unit-tests, disable Numba JIT, otherwise Coverage wont reach the actual Python code
#  - python setup.py install
#  - python -m unittest discover  -p "*_test.py"
#  - coverage run -m unittest discover  -p "*_test.py"
#
#after_success:
#  - pip install codecov
#  - codecov
