
name: hypernets_processor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7*
  #
  # dependencies (in alphabetical order)
  #
  - numpy >= 1.18.1
  - scipy >= 1.4.1
  - netcdf4 >= 1.5.3
  - xarray >=0.8.2
  #
  # for testing only
  #
  # - pytest >=3.1,<3.2
  # - pytest-cov >=2.5.1,<2.6
