
name: hypernets_processor
channels:
  - conda-forge
  - defaults
  - coecms
dependencies:
  - python=3.7*
  #
  # dependencies (in alphabetical order)
  #
  - numpy >= 1.18.1
  - scipy >= 1.4.1
  - netcdf4 >= 1.5.3
  - xarray >=0.8.2
  - schedule>=0.6.0
  - matplotlib >= 3.1.3
  - pysolar >= 0.8
  - dataset
  - sqlalchemy-utils
  - psycopg2
  - pip
  - pip:
      - punpy>=0.2.1
  #
  # for testing only
  #
  - pytest >=5.4.1
  - pytest-cov >=2.8.1
